#!/bin/sh -e

export DESTDIR="$1"

sed "s#/usr/local#/usr#" \
    Makefile > _
mv -f _ Makefile

sed -ie '34,35d;36d' main.c
sed -i '34i #define noop' main.c

sed "s#noop,#noop#" \
    main.c > _
mv -f _ main.c

make
make install
