#!/bin/sh -e

export DESTDIR="$1"

sed "s#/usr/local#/usr#" \
    config.mk > _
mv -f _ config.mk

sed "s#ENABLE_XWAYLAND = 1#ENABLE_XWAYLAND = 0#" \
    config.mk > _
mv -f _ config.mk

make
make install
