#!/bin/sh -e

mkdir -p ./firmware

./copy-firmware.sh ./firmware

mkdir -p "$1/usr/lib/firmware/intel-ucode/"
mkdir -p "$1/usr/lib/firmware/nvidia/"

cp intel-ucode/06-b7-01 "$1/usr/lib/firmware/intel-ucode/"
cp -Lr firmware/nvidia/ad104/ "$1/usr/lib/firmware/nvidia/"
