#!/bin/sh -e

export DESTDIR="$1"

sed "s#/usr/local#/usr#" \
    Makefile > _
mv -f _ Makefile

sed "s#SSIZE_MAX#SIZE_MAX#" \
    src/wl.c > _
mv -f _ src/wl.c

make window_protocol=wayland libutf8proc=off
make install
