#!/bin/sh -e

export DESTDIR="$1"

sed "s#/usr/local#/usr#" \
    Makefile > _
mv -f _ Makefile

sed "s#ENABLE_DEBUG    = 1#ENABLE_DEBUG    = 0#" \
    config.mk > _
mv -f _ config.mk

make
make install
